# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WU4iCTAnyPsFpV6q-ept2ZwVkY3n4M47
"""

def demo(name, age):
  print(name, age)
demo("Thanh Hoa", 36)

L = eval(input("Nhập danh sách: "))
print('So nguyen to: ', L[0])

a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 8, 2]
min = len(b) if len(a)>len(b) else len(a)
c = a if len(a)>len(b) else b
for i in range(min):
  c[i] = a[i] + b[i]
print(c)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = [];
for x in fruits:
  if "a" in x:
    newlist.append(x)
print(newlist)

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = []

for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

import numpy as np

def create_arrays(n):

  n = int(input("Nhập vao số lượng phần tử: "))
  a = []
  for i in range(n):
    x = int(input(f"Nhập vào phần tử thứ {i+1}: "))
    a.append(x)
  a = np.array(a)
  b = a[a % 2 == 0]
  return a, b

n = 10
array_a, array_b = create_arrays(n)

print("Mảng a:", array_a)
print("Mảng b (chỉ chứa phần tử chẵn):", array_b)

a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 8, 2]
min = len(b) if len(a) > len(b) else len(a)
c = a if len(a) > len(b) else b
for i in range(min):
  c[i] = a[i] + b[i]
print(c)

import random


def tao_mang_ngau_nhien(m, n, min_val=0, max_val=100):
    a = [[random.randint(min_val, max_val) for i in range(n)] for j in range(m)]
    return a


def xuat_dong(a, k):
    if 0 <= k < len(a):
        return a[k]
    else:
        return None


def xuat_cot(a, k):
    if len(a) == 0 or k < 0 or k >= len(a[0]):
        return None
    return [row[k] for row in a]


def dong_tong_lon_nhat(a):
    max_sum = None
    max_row_index = -1
    for i in range(len(a)):
        s = sum(a[i])
        if max_sum is None or s > max_sum:
            max_sum = s
            max_row_index = i
    return max_row_index, max_sum


def cot_tich_nho_nhat(a):
    if len(a) == 0:
        return None, None
    m = len(a)
    n = len(a[0])
    min_product = None
    min_col_index = -1
    for col in range(n):
        product = 1
        for row in range(m):
            product *= a[row][col]
        if min_product is None or product < min_product:
            min_product = product
            min_col_index = col
    return min_col_index, min_product


def xuat_dong_chan_cot_le(a):
    m = len(a)
    if m == 0:
        return 0
    n = len(a[0])
    result = []
    for i in range(m):
        if i % 2 == 0:
            for j in range(n):
                if j % 2 == 1:
                    result.append(a[i][j])
    return result


def trung_binh_chi_phan_tu_chan_dong_le(a):
    m = len(a)
    if m == 0:
        return 0
    n = len(a[0])
    total = 0
    count = 0
    for i in range(m):
        if i % 2 == 1:
            for j in range(n):
                if a[i][j] % 2 == 0:
                    total += a[i][j]
                    count += 1
    return total / count if count > 0 else 0


def trung_binh_phan_tu_bien(a):
    m = len(a)
    if m == 0:
        return 0
    n = len(a[0])
    bien_elements = []
    for i in range(m):
        for j in range(n):
            if i == 0 or i == m - 1 or j == 0 or j == n - 1:
                bien_elements.append(a[i][j])
    if len(bien_elements) == 0:
        return 0
    return sum(bien_elements) / len(bien_elements)


def trung_binh_tich_phan_tu_khong_bien(a):
    m = len(a)
    if m == 0:
        return 0
    n = len(a[0])
    product_list = []
    for i in range(1, m-1):
        for j in range(1, n-1):
            product_list.append(a[i][j])
    if len(product_list) == 0:
        return 0
    product = 1
    for num in product_list:
        product *= num
    return product / len(product_list)


def in_ma_tran(a):
    for row in a:
        print(' '.join(map(str, row)))


m, n = 4, 5
a = tao_mang_ngau_nhien(m, n, 1, 10)
print("Ma trận a:")
in_ma_tran(a)

print("\nCác phần tử dòng 2:", xuat_dong(a, 2))
print("Các phần tử cột 3:", xuat_cot(a, 3))
print("Dòng có tổng lớn nhất:", dong_tong_lon_nhat(a))
print("Cột có tích nhỏ nhất:", cot_tich_nho_nhat(a))
print("Phần tử dòng chẵn cột lẻ:", xuat_dong_chan_cot_le(a))
print("Trung bình cộng phần tử chẵn dòng lẻ:", trung_binh_chi_phan_tu_chan_dong_le(a))
print("Trung bình cộng phần tử biên:", trung_binh_phan_tu_bien(a))
print("Trung bình tích phần tử không thuộc biên:", trung_binh_tich_phan_tu_khong_bien(a))