# -*- coding: utf-8 -*-
"""buoi3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LeBJaSxlyTrNZmNqe3gJpB92o3hp0rsL
"""

class String:
  def _init_(self):
    self.str = " "
  def get(self):
    self.str = input("Nhap vao chuoi: ")
  def put(self):
    print("Chuoi vua nhap: ", self.str)
chuoi = String()
chuoi.get()
chuoi.put()

class tap_hop:
    def __init__(self):
        self.ds = []

    def phuong_thuc_f1(self):
        n = int(input("Nhap vao so phan tu: "))
        self.ds = []
        for i in range(n):
            x = int(input("Nhap vao phan tu: "))
            self.ds.append(x)
        self.ds.sort()

    def phuong_thuc_f2(self):
        ket_qua = [[]]
        for so in self.ds:
            tap_moi = []
            for tap in ket_qua:
                tap_copy = tap.copy()
                tap_copy.append(so)
                tap_moi.append(tap_copy)
            ket_qua.extend(tap_moi)

        print("Cac tap con co the co la:")
        for s in ket_qua:
            print(s)

th1 = tap_hop()
th1.phuong_thuc_f1()
th1.phuong_thuc_f2()

class NhanVien:
    def __init__(self):
        self.ten = ""
        self.tuoi = 0
        self.dia_chi = ""
        self.luong = 0.0
        self.tong_gio_lam = 0

    def inputInfo(self):
        self.ten = input("Nhap ten: "
        )
        self.tuoi = int(input("Nhap tuoi: "))
        self.dia_chi = input("Nhap dia chi: ")
        self.luong = float(input("Nhap luong: "))
        self.tong_gio_lam = int(input("Nhap tong so gio lam: "))

    def printInfo(self):
        print("Ten:", self.ten)
        print("Tuoi:", self.tuoi)
        print("Dia chi:", self.dia_chi)
        print("Luong:", self.luong)
        print("Tong gio lam:", self.tong_gio_lam)

    def tinhThuong(self):
        if self.tong_gio_lam >= 200:
            return self.luong * 0.2
        elif self.tong_gio_lam >= 100:
            return self.luong * 0.1
        else:
            return 0

nv = NhanVien()
nv.inputInfo()
nv.printInfo()
print("Tien thuong:", nv.tinhThuong())

class tam_giac:
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c
    def loai_tam_giac(self):
      if self.a == self.b == self.c:
        return "Tam giác đều"
      elif self.a == self.b or self.a == self.c or self.b == self.c:
        return "Tam giác cân"
      else:
        return "Tam giác thường"
    def   chu_vi(self):
        return self.a + self.b + self.c
    def dien_tich(self):
        p = self.chu_vi() / 2
        return (p * (p - self.a) * (p - self.b) * (p - self.c)) ** 0.5
a = int(input("Nhập cạnh a: "))
b = int(input("Nhập cạnh b: "))
c = int(input("Nhập cạnh c: "))
tam_giac1 = tam_giac(a, b, c)
print("Loại tam giác:", tam_giac1.loai_tam_giac())
print("Chu vi tam giác:", tam_giac1.chu_vi())
print("Diện tích tam giác:", tam_giac1.dien_tich())

class Person:
    def __init__(self, name, country, dob):
      self.name = name
      self.country = country
      self.dob = dob
    def get_age(self, current_year):
      return current_year - self.dob
    def display_info(self, current_year):
      print("Name: ", self.name)
      print("Country: ", self.country)
      print("DOB: ", self.dob)
      print("Age: ", self.get_age(current_year))

p1 = Person("John", "USA", 1990)
p1.display_info(2025)