# -*- coding: utf-8 -*-
"""Chào mừng bạn đến với Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

def create():
    n = int(input("Nhập vào số lượng phần tử: "))
    a = []
    for i in range(n):
        x = int(input(f"Nhập vào phần tử thứ {i+1}: "))
        a.append(x)


    b = []
    for x in a:
        if x % 2 == 0:
            b.append(x)

    return a, b


a, b = create()
print("Mảng a:", a)
print("Mảng b (chẵn):", b)

a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]
min = len(b) if len(a)>len(b) else len(a)
c = a if len(a) > len(b) else b
for i in range(min):
  c[i] = a[i] + b[i]
print(c)

import random

def nhapmang(m, n, min_val=0, max_val=100):
    a = [[random.randint(min_val, max_val) for i in range(n)]for j in range(m)]
    return a

def xuat_dong_k(a, k):
    if 0 <= k < len(a):
        print(a[k])
    else:
        print("Vị trí không hợp lệ")

def xuat_cot_k(a, k):
    if k < len(a[0]):
        for i in range(len(a)):
            print(a[i][k], end=" ")
        print()
    else:
        print("Vị trí không hợp lệ")

def dong_tong_lon_nhat(a):
    max_sum = None
    max_row = -1
    for i in range(len(a)):
        s = sum(a[i])
        if max_sum is None or s > max_sum:
            max_sum = s
            max_row = i
    return max_row, max_sum

def cot_tich_lon_nhat(a):
    if len(a) == 0 or len(a[0]) == 0:
        return None
    max_kq = None
    max_col = -1
    for j in range(len(a[0])):
        kq = 1
        for i in range(len(a)):
            kq *= a[i][j]
        if max_kq is None or kq > max_kq:
            max_kq = kq
            max_col = j
    return max_col, max_kq

def dong_chan_cot_le(a):
    if len(a) == 0 or len(a[0]) == 0:
        return None
    kq = []
    for i in range(len(a)):
        if i % 2 == 0:
            for j in range(len(a[0])):
                if j % 2 == 1:
                    kq.append(a[i][j])
    return kq

def trung_binh_phan_tu_chan_dong_le(a):
    if len(a) == 0 or len(a[0]) == 0:
        return None
    tong = 0
    dem = 0
    for i in range(len(a)):
        if i % 2 == 1:
            for j in range(len(a[0])):
                if a[i][j] % 2 == 0:
                    tong += a[i][j]
                    dem += 1
    return tong / dem if dem > 0 else None

def trung_binh_bien(a):
    if len(a) == 0 or len(a[0]) == 0:
        return None
    bien = []
    for i in range(len(a)):
        for j in range(len(a[0])):
            if i == 0 or i == len(a) - 1 or j == 0 or j == len(a[0]) - 1:
                bien.append(a[i][j])
    if len(bien) == 0:
        return None
    return sum(bien) / len(bien)

def trung_binh_khong_bien(a):
    if len(a) == 0 or len(a[0]) == 0:
        return None
    khong_bien = []
    for i in range(1, len(a) - 1):
        for j in range(1, len(a[0]) - 1):
            khong_bien.append(a[i][j])
    if len(khong_bien) == 0:
        return None
    kq = 1
    for num in khong_bien:
        kq *= num
    return kq / len(khong_bien)

def in_matrix(a):
    for i in range(len(a)):
        for j in range(len(a[0])):
            print(a[i][j], end=" ")
        print()


m, n = 4, 5
a = nhapmang(m, n, 1, 10)
print("Ma trận a:")
in_matrix(a)


k = 2
print(f"\nDòng thứ {k}:")
xuat_dong_k(a, k)

print(f"Cột thứ {k}:")
xuat_cot_k(a, k)

print("\nDòng tổng lớn nhất:", dong_tong_lon_nhat(a))
print("Cột tích lớn nhất:", cot_tich_lon_nhat(a))
print("Các phần tử dòng chẵn, cột lẻ:", dong_chan_cot_le(a))
print("Trung bình phần tử chẵn ở dòng lẻ:", trung_binh_phan_tu_chan_dong_le(a))
print("Trung bình các phần tử biên:", trung_binh_bien(a))
print("Trung bình (theo tích) các phần tử không biên:", trung_binh_khong_bien(a))