# -*- coding: utf-8 -*-
"""Bản sao của Chào mừng bạn đến với Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UiANywvg7XcMC4jIsjubLYHgyiSWBp1s
"""

a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]
min = len(b) if len(a) > len(b) else len(a)
c = a.copy() if len(a) > len(b) else b.copy()
for i in range(min):
  c[i] = a[i] if a[i] < b[i] else b[i]
print(c)

def create_array():
  n = int(input("Nhap vao so luong phan tu ne: "))
  a = []
  for i in range(n):
    x = int(input(f"Nhap vao gia tri thu {i}: "))
    a.append(x)
  m = int(input("Nhap vao so luong phan tu ne: "))
  b = []
  for i in range(m):
    y = int(input(f"Nhap vao gia tri thu {i}: "))
    b.append(y)
  c = []
  for x in a:
    if x % 2 == 1:
      c.append(x)
  for y in b:
    if y % 2 == 0:
      c.append(y)

  return a, b, c
a, b, c = create_array()
print("Mang a: ", a)
print("Mang b: ", b)
print("Mang c: ", c)

import random
def creat_array(n, min_val = -10, max_val = 10):
  a = [[random.randint(min_val, max_val) for i in range(n)] for j in range(n)]
  return a
def tam_giac_tren_cheo_phu(a):
  n = len(a)
  return [a[i][j] for i in range(n) for j in range(n) if i+j <= n-1]
def tong_tam_giac_tren_cheo_phu(a):
  return sum(tam_giac_tren_cheo_phu(a))
def chuyen_am_thanh_tri_tuyet_doi(a):
  if len(a) == 0:
    return None, None
  for i in range(len(a)):
    for j in range(len(a[i])):
      if a[i][j] < 0:
         a[i][j] = abs(a[i][j])
  return a
def thay_chan_thanh_x(a):
  x = int(input("Nhap vao gia tri x: "))
  for i in range(len(a)):
    for j in range(len(a[i])):
      if a[i][j] % 2 == 0:
        a[i][j] = x
  return a
def kiem_tra_toan_chan(a):
  for i in range(len(a)):
    for j in range(len(a[i])):
      if a[i][j] % 2 != 0:
        return False
  return True
def kiem_tra_doi_xung(a):
  for i in range(len(a)):
    for j in range(len(a[i])):
      if a[i][j] != a[j][i]:
        return False
  return True
def kiem_tra_duong_cheo_chinh_tang_dan(a):
  if len(a) == 0:
    return None
  n = len(a)
  for i in range(1, n):
    if a[i][i] <= a[i-1][i-1]:
      return False
  return True
def tam_giac_duoi_duong_cheo_phu(a):
  n = len(a)
  return [a[i][j] for i in range(n) for j in range(n) if i+j >= n-1]
def kiem_tra_duong_cheo_phu_giam_dan(a):
  if len(a) == 0:
    return None
  n = len(a)
  for i in range(1, n):
        if a[i][n-1-i] >= a[i-1][n-i]:
            return False
  return True
def in_ma_tran(a):
  for i in range(len(a)):
        for j in range(len(a[i])):
            print(a[i][j], end=" ")
        print()
n = 3
a = creat_array(n, -10, 10)
print("Ma trận a:")
in_ma_tran(a)

print("\nTam giác trên đường chéo phụ:", tam_giac_tren_cheo_phu(a))
print("Tổng tam giác trên đường chéo phụ:", tong_tam_giac_tren_cheo_phu(a))
print("\nChuyển âm thành trị tuyệt đối:")
in_ma_tran(chuyen_am_thanh_tri_tuyet_doi(a))
print("\nThay số chẵn bằng x:")
in_ma_tran(thay_chan_thanh_x(a))
print("\nKiểm tra toàn chẵn:", kiem_tra_toan_chan(a))
print("Kiểm tra ma trận đối xứng:", kiem_tra_doi_xung(a))
print("Đường chéo chính tăng dần:", kiem_tra_duong_cheo_chinh_tang_dan(a))
print("Tam giác dưới đường chéo phụ:", tam_giac_duoi_duong_cheo_phu(a))
print("Đường chéo phụ giảm dần:", kiem_tra_duong_cheo_phu_giam_dan(a))